name: Facebook Blog
description: Plugin will download your Facebook Page RSS feed and add them as published (optional) blog node posts

author: Darren Moore
authorEmail: darren.m@firecreekweb.com
authorUrl: http://www.firecreekweb.com
